app/models.py
from app import db

class User(db.Model):
    id = db.Column(db.Integer , primary_key=True)
    username = db.Column(db.String, unique=True, index = True)
    email = db.Column(db.String, unique=True, index = True)
    password = db.Column(db.String)

    def __repr__(self):
        return f"{self.username}({self.email})"

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager, current_user
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


db = SQLAlchemy()
migrate = Migrate()


def create_app():
    """
    Application factory method to create application
    :return: Flask application configured object
    """

    # create instance of Flask object
    app = Flask(__name__)

    # update application config from Config class in config.py
    app.config.from_object(Config)

    # install extensions
    db.init_app(app)
    migrate.init_app(app, db)

    # register blueprints here
    from .main import bp as main_bp
    app.register_blueprint(main_bp)

    from .auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from .fake import bp as fake_bp
    app.register_blueprint(fake_bp)

    from . import models

    from .models import User

    @app.context_processor
    def context_processor():
        return dict(
            current_user=current_user
        )
    return app


# create instance of application
app = create_app()

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)
from app.main import routes

app/main/routes.py
from app import db
from app.main import bp
from flask import render_template

from app.models import User


@bp.route("/")
@bp.route("/index")
def index():
    users_data = [
        {
            "username": "Zh",
            "email": "Zh@ll.ll"
        },
        {
            "username": "Ton",
            "email": "Ton@ll.ll"
        },
        {
            "username": "De",
            "email": "De@ll.ll"
        },
        {
            "username": "Tan",
            "email": "Tan@ll.ll"
        },
    ]
    for u in users_data:
        user = (
            db.session.query(User)
                .filter(
                User.username == u.get('username'),
                User.email == u.get('email')
            ).first()
        )
        if user:
            continue

        user = User(
            username=u.get('username'),
            email=u.get('email')
        )
        db.session.add(user)
    db.session.commit()

    users_query = db.session.query(User)
    users = users_query.all()
    print(users)
    return render_template("index.html", users=users)


@bp.route("/about")
def about():
    return render_template("about.html")

app/templates/about.html
{% extends "base.html" %}

{% block title %}
        About
{% endblock %}

{% block content %}
        About Page
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="">
<head>
    <title>
        {% block title %}
            {% if title %}
            {{ title }}
            {% else %}
                Social Network
            {% endif %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Social Network</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                <li class="nav-item{% if active == 'index' %} active{% endif %}">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item me-2">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    {% endif %}
                </li>
                {% if not current_user.is_authenticated %}
                <li class="nav-item me-2">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == "error" %}
            <div class="alert alert-danger">{{ message }}</div>
          {% elif category == "success" %}
            <div class="alert alert-success">{{ message }}</div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <ul>
    {% for user in users %}
        <li>{{ user.username }} - {{ user.email }}</li>
    {% endfor %}
    </ul>
{% endblock %}